import { useEffect, useMemo, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { Eye, Landmark, Printer, Search, X } from "lucide-react";
import PageHeader, { Empty, money, StatusBadge } from "../components/PageHeader";
import { fetchPayrollBatch, fetchPayrollBatches, payBatch } from "../features/payroll/payrollThunks";

const monthName = (month) => new Date(2026, Number(month) - 1).toLocaleString("en", { month: "long" });
const period = (batch) => `${monthName(batch.month)} ${batch.year}`;

export default function ApprovedPayrollsPage() {
  const dispatch = useDispatch();
  const { batches, activeBatch, loading, error } = useSelector((state) => state.payroll);
  const [month, setMonth] = useState(""); const [year, setYear] = useState(""); const [search, setSearch] = useState(""); const [payslip, setPayslip] = useState(null);
  useEffect(() => { dispatch(fetchPayrollBatches()); }, [dispatch]);
  const approvedBatches = useMemo(() => batches.filter((batch) => ["APPROVED", "PAID"].includes(batch.status) && (!month || Number(batch.month) === Number(month)) && (!year || String(batch.year) === year)), [batches, month, year]);
  const employees = useMemo(() => (activeBatch?.employees || []).filter((employee) => `${employee.full_name} ${employee.account_number}`.toLowerCase().includes(search.toLowerCase())), [activeBatch, search]);
  const markPaid = async () => { if (!activeBatch || !window.confirm(`Mark the ${period(activeBatch)} payroll batch as paid?`)) return; try { await dispatch(payBatch(activeBatch.id)).unwrap(); await dispatch(fetchPayrollBatches()); } catch { /* Error is rendered from Redux. */ } };
  const printBatch = () => window.print();
  return <><PageHeader title="Approved payrolls" subtitle="Review approved payroll batches and prepare employee bank disbursements."><div className="flex flex-wrap gap-2"><select aria-label="Filter by month" className="field" value={month} onChange={(e) => setMonth(e.target.value)}><option value="">All months</option>{Array.from({ length: 12 }, (_, i) => <option key={i} value={i + 1}>{monthName(i + 1)}</option>)}</select><input aria-label="Filter by year" className="field w-28" type="number" placeholder="All years" value={year} onChange={(e) => setYear(e.target.value)} /></div></PageHeader><section className="space-y-6 p-4 sm:p-6">{error && <p className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700 dark:bg-rose-950/40 dark:text-rose-300">{error}</p>}<div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="border-b border-slate-100 px-5 py-4 dark:border-slate-800"><h2 className="font-semibold">Approved payroll batches</h2><p className="mt-1 text-sm text-slate-500">Only approved and paid periods are shown here.</p></div>{loading && !batches.length ? <Empty>Loading approved payroll batches…</Empty> : approvedBatches.length ? <table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500 dark:bg-slate-800/60"><tr>{["Period", "Total employees", "Total net salary", "Total deductions", "Status", "Action"].map((label) => <th className="px-4 py-3 sm:px-5" key={label}>{label}</th>)}</tr></thead><tbody>{approvedBatches.map((batch) => <tr className="border-t border-slate-100 dark:border-slate-800" key={batch.id}><td className="px-4 py-4 font-semibold sm:px-5">{period(batch)}</td><td className="px-4 py-4 sm:px-5">{batch.employee_count} employees</td><td className="px-4 py-4 font-medium sm:px-5">{money(batch.total_net)} ETB</td><td className="px-4 py-4 sm:px-5">{activeBatch?.id === batch.id ? `${money(activeBatch.grand_totals?.total_deductions)} ETB` : "Open batch to view"}</td><td className="px-4 py-4 sm:px-5"><StatusBadge status={batch.status} /></td><td className="px-4 py-4 sm:px-5"><button className="inline-flex items-center gap-1 font-semibold text-blue-600" onClick={() => { setSearch(""); dispatch(fetchPayrollBatch(batch.id)); }}><Eye size={16} />View batch</button></td></tr>)}</tbody></table> : <Empty>No approved or paid payroll batches match these filters.</Empty>}</div>{activeBatch && <BatchDetail batch={activeBatch} employees={employees} search={search} setSearch={setSearch} loading={loading} onPay={markPaid} onPrint={printBatch} onPayslip={setPayslip} />}</section>{payslip && <PayslipModal payroll={payslip} batch={activeBatch} close={() => setPayslip(null)} />}</>;
}

function BatchDetail({ batch, employees, search, setSearch, loading, onPay, onPrint, onPayslip }) {
  const totals = batch.grand_totals || {};
  return <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4 border-b border-slate-100 pb-5 dark:border-slate-800"><div><p className="text-sm text-slate-500">Payroll Disbursement Detail</p><h2 className="text-xl font-bold">{period(batch)}</h2><div className="mt-2"><StatusBadge status={batch.status} /></div></div><div className="flex flex-wrap gap-2"><button className="button bg-slate-700 hover:bg-slate-800" onClick={onPrint}><Printer size={16} />Print table</button>{batch.status === "APPROVED" && <button className="button" disabled={loading} onClick={onPay}><Landmark size={16} />Mark entire batch as paid</button>}</div></div><div className="my-5 grid gap-3 sm:grid-cols-3"><Stat label="Total net salary payable" value={`${money(totals.total_net_salary ?? batch.total_net)} ETB`} /><Stat label="Total employees" value={batch.employees?.length || 0} /><Stat label="Current status" value={<StatusBadge status={batch.status} />} /></div><label className="relative mb-4 block max-w-md"><Search className="absolute right-3 top-3 text-slate-400" size={17} /><input className="field w-full pr-9" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search employee or account number" /></label><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500 dark:bg-slate-800/60"><tr>{["#", "Employee name", "Account number", "Net salary (ETB)", "Payment status"].map((label) => <th className="px-4 py-3" key={label}>{label}</th>)}</tr></thead><tbody>{employees.map((employee, index) => <tr className="border-t border-slate-100 dark:border-slate-800" key={employee.id}><td className="px-4 py-4 text-slate-500">{index + 1}</td><td className="px-4 py-4 font-semibold"><button className="text-left hover:text-blue-600" onClick={() => onPayslip(employee)}>{employee.full_name}</button></td><td className="px-4 py-4 font-mono">{employee.account_number || "—"}</td><td className="px-4 py-4 font-semibold">{money(employee.net_salary)}</td><td className="px-4 py-4"><StatusBadge status={employee.payment_status || batch.status} /></td></tr>)}</tbody></table>{!employees.length && <Empty>No bank transfer records match your search.</Empty>}</div></section>;
}
function Stat({ label, value }) { return <div className="rounded-xl bg-slate-50 p-4 dark:bg-slate-800/60"><p className="text-sm text-slate-500">{label}</p><div className="mt-1 font-semibold">{value}</div></div>; }
function PayslipModal({ payroll, batch, close }) { const deductions = [["Income tax", payroll.income_tax], ["Staff pension (7%)", payroll.employee_pension_staff], ["Employer pension (11%) · company contribution", payroll.employer_pension], ["Attendance deduction", payroll.unpaid_days_deduction], ["Total deductions (excludes employer pension)", payroll.total_deductions]]; return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/50 p-4 print:static print:bg-transparent"><div className="mx-auto my-6 max-w-3xl rounded-2xl bg-white shadow-2xl dark:bg-slate-900 print:my-0 print:shadow-none"><div className="flex justify-end gap-2 p-4 print:hidden"><button className="button bg-slate-700 hover:bg-slate-800" onClick={() => window.print()}><Printer size={16} />Print</button><button className="rounded-xl p-2 text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800" aria-label="Close payslip" onClick={close}><X /></button></div><article className="p-5 sm:p-8 print:p-0"><div className="flex justify-between border-b border-slate-200 pb-5 dark:border-slate-800"><div><h2 className="text-xl font-bold">Ethiopian Assemblies of God</h2><p className="text-sm text-slate-500">Employee payroll payslip</p></div><div className="text-right"><b>{period(batch)}</b><div className="mt-2"><StatusBadge status={payroll.payment_status || batch.status} /></div></div></div><div className="my-5 grid grid-cols-2 gap-4 text-sm"><p><span className="text-slate-500">Employee</span><br /><b>{payroll.full_name}</b></p><p><span className="text-slate-500">Payment date</span><br /><b>{payroll.payment_date ? String(payroll.payment_date).slice(0, 10) : "Pending payment"}</b></p></div><SlipRows title="Earnings" rows={[["Basic salary", payroll.basic_salary], ["Transport allowance", payroll.transport_allowance], ["Mobile allowance", payroll.mobil_card_allowance], ["Gross salary", payroll.gross_salary]]} /><SlipRows title="Deductions from your pay" rows={deductions} /><div className="mt-5 flex justify-between rounded-xl bg-emerald-50 p-4 font-bold text-emerald-950 dark:bg-emerald-400/10 dark:text-emerald-100"><span>Final net pay</span><span>{money(payroll.net_salary)} ETB</span></div></article></div></div>; }
function SlipRows({ title, rows }) { return <div className="mt-5"><h3 className="mb-2 font-semibold">{title}</h3>{rows.map(([label, value]) => <div className="flex justify-between border-t border-slate-100 py-2 text-sm dark:border-slate-800" key={label}><span>{label}</span><span>{money(value)} ETB</span></div>)}</div>; }
