import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { CalendarDays, WalletCards } from "lucide-react";
import PageHeader, { money } from "../components/PageHeader";
import { fetchMyAttendance, fetchMyStats } from "../features/attendance/attendanceThunks";
import { fetchMyPayslip } from "../features/payroll/payrollThunks";
const now = new Date(), stamp = (d) => d.toISOString().slice(0,10);
export default function EmployeeDashboard() { const dispatch = useDispatch(); const { user } = useSelector((s) => s.auth); const { myStats, mine } = useSelector((s) => s.attendance); const { payslip } = useSelector((s) => s.payroll); useEffect(() => { const y=now.getFullYear(),m=now.getMonth()+1; dispatch(fetchMyStats({month:m,year:y})); dispatch(fetchMyPayslip({month:m,year:y})); dispatch(fetchMyAttendance({startDate:stamp(new Date(y,m-1,1)), endDate:stamp(new Date(y,m,0))})); }, [dispatch]);
 const records = Object.fromEntries(mine.map((x) => [String(x.date).slice(0,10), x.status])); return <><PageHeader title={`Welcome, ${user?.full_name || "Employee"}`} subtitle="Your attendance and payroll overview."/><section className="p-6"><div className="grid gap-4 md:grid-cols-3"><div className="card"><WalletCards className="mb-3 text-blue-600"/><p>Current net salary</p><strong>{money(payslip?.net_salary)} ETB</strong></div><div className="card"><CalendarDays className="mb-3 text-emerald-600"/><p>Days present</p><strong>{myStats?.present_count || 0}</strong></div><div className="card"><CalendarDays className="mb-3 text-rose-600"/><p>Unpaid leave</p><strong>{myStats?.unpaid_leave_count || 0}</strong></div></div><div className="mt-6 rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 className="font-semibold">Personal attendance · {now.toLocaleString("en",{month:"long",year:"numeric"})}</h2><div className="mt-4 grid grid-cols-7 gap-2 sm:grid-cols-10">{Array.from({length:new Date(now.getFullYear(),now.getMonth()+1,0).getDate()},(_,i)=>{const date=stamp(new Date(now.getFullYear(),now.getMonth(),i+1));const status=records[date];const color=status === "PRESENT" ? "bg-emerald-100 text-emerald-700" : status === "UNPAID_LEAVE" || status === "ABSENT" ? "bg-rose-100 text-rose-700" : status ? "bg-slate-200 text-slate-600" : "bg-slate-50 text-slate-400 dark:bg-slate-800"; return <div className={`rounded-lg p-2 text-center text-xs ${color}`} key={date}><b>{i+1}</b><span className="block">{status === "PRESENT" ? "P" : status === "UNPAID_LEAVE" || status === "ABSENT" ? "A" : status ? "H" : "–"}</span></div>})}</div></div></section></>; }
