import { useCallback, useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { CalendarDays, Printer } from "lucide-react";
import PageHeader, { Empty, money, StatusBadge } from "../components/PageHeader";
import { fetchMyPayslip } from "../features/payroll/payrollThunks";

const now = new Date();
const monthName = (month) => new Date(2026, Number(month) - 1).toLocaleString("en", { month: "long" });
export default function PayslipView() {
  const dispatch = useDispatch(); const { payslip, loading, error } = useSelector((s) => s.payroll); const user = useSelector((s) => s.auth.user);
  const [month, setMonth] = useState(now.getMonth() + 1); const [year, setYear] = useState(now.getFullYear());
  const load = useCallback(() => dispatch(fetchMyPayslip({ month, year: Number(year) })), [dispatch, month, year]);
  useEffect(() => { load(); }, [load]);
  return <><PageHeader title="My payslip" subtitle="Find and print your payroll by month and year."><div className="flex flex-wrap gap-2 print:hidden"><select aria-label="Payslip month" className="field" value={month} onChange={(e) => setMonth(+e.target.value)}>{Array.from({ length: 12 }, (_, i) => <option key={i} value={i + 1}>{monthName(i + 1)}</option>)}</select><input aria-label="Payslip year" className="field w-24" type="number" min="2000" max="2100" value={year} onChange={(e) => setYear(e.target.value)} /><button className="button" disabled={loading} onClick={load}><CalendarDays size={17} />Find</button>{payslip && <button className="button bg-slate-700 hover:bg-slate-800" onClick={() => window.print()}><Printer size={17} />Print</button>}</div></PageHeader><section className="p-4 sm:p-6 print:p-0">{loading ? <Empty>Loading payslip…</Empty> : error ? <Empty>{error}</Empty> : !payslip ? <Empty>No payslip has been generated for {monthName(month)} {year}. Please check another period or contact payroll.</Empty> : <article className="mx-auto max-w-3xl rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:p-8 print:border-0 print:p-0"><div className="flex justify-between border-b border-slate-200 pb-5 dark:border-slate-800"><div><h2 className="text-xl font-bold">Ethiopian Assemblies of God</h2><p className="text-sm text-slate-500">Employee payroll payslip</p></div><div className="text-right"><b>{monthName(payslip.month)} {payslip.year}</b><div className="mt-2"><StatusBadge status={payslip.payment_status || payslip.batch_status} /></div></div></div><div className="my-5 grid grid-cols-2 gap-4 text-sm"><p><span className="text-slate-500">Employee</span><br /><b>{user?.full_name}</b></p><p><span className="text-slate-500">Payment date</span><br /><b>{payslip.payment_date ? String(payslip.payment_date).slice(0, 10) : "Pending payment"}</b></p></div><Breakdown title="Earnings" rows={[["Basic salary", payslip.basic_salary], ["Transport allowance", payslip.transport_allowance], ["Mobile allowance", payslip.mobil_card_allowance], ["Gross salary", payslip.gross_salary]]} /><Breakdown title="Deductions from your pay" rows={[["Income tax", payslip.income_tax], ["Staff pension (7%)", payslip.employee_pension_staff], ["Employer pension (11%) · company contribution", payslip.employer_pension], ["Attendance deduction", payslip.unpaid_days_deduction], ["Total deductions (excludes employer pension)", payslip.total_deductions]]} /><div className="mt-5 flex justify-between rounded-xl bg-emerald-50 p-4 font-bold text-emerald-950 dark:bg-emerald-400/10 dark:text-emerald-100"><span>Final net pay</span><span>{money(payslip.net_salary)} ETB</span></div></article>}</section></>;
}
function Breakdown({ title, rows }) { return <div className="mt-5"><h3 className="mb-2 font-semibold">{title}</h3>{rows.map(([label, value]) => <div className="flex justify-between border-t border-slate-100 py-2 text-sm dark:border-slate-800" key={label}><span>{label}</span><span>{money(value)} ETB</span></div>)}</div>; }
